### PR TITLE
Add script for creating MCC->MNC->Operator map in Kotlin format

### PR DESCRIPTION
**Pull request by andereld**

### CODE REVIEW

**Comment by jorunfa** [comment]
Do you have some example output (a couple of lines) you could share?

**Comment by jorunfa** [comment]
Or is that what I see here? https://github.com/omnicate/loltel/pull/35752/files#diff-6da03d13dda34eeb82dad13bec98bae71a5aa694271870146d5ec627f695395d

**Comment by andereld** [comment]
> Or is that what I see here? https://github.com/omnicate/loltel/pull/35752/files#diff-6da03d13dda34eeb82dad13bec98bae71a5aa694271870146d5ec627f695395d

Yep, that is indeed what you see there.

**Comment by andereld** [comment]
But for completeness, here's the beginning of the script's output:

```
"202" to mapOf(
    "01" to Operator("COSMOTE - Mobile Telecommunications S.A.", "GRCCO"),
    "14" to Operator("CYTA", "GRCCT"),
    "05" to Operator("Vodafone Greece", "GRCPF"),
    "10" to Operator("Wind Hellas Telecommunications S.A.", "GRCSH"),
),
"204" to mapOf(
    "20" to Operator("T-Mobile Netherlands B.V", "NLDDT"),
    "04" to Operator("Vodafone Libertel B.V.", "NLDLT"),
    "16" to Operator("T-Mobile Netherlands B.V", "NLDPN"),
    "08" to Operator("KPN Mobile The Netherlands B.V.", "NLDPT"),
),
"206" to mapOf(
    "20" to Operator("Telenet", "BELKO"),
    "10" to Operator("Orange S.A.", "BELMO"),
    "01" to Operator("Belgacom Mobile", "BELTB"),
),
"208" to mapOf(
    "01" to Operator("Orange S.A.", "FRAF1"),
    "10" to Operator("Altice", "FRAF2"),
    "20" to Operator("Bouygues Telecom", "FRAF3"),
    "15" to Operator("Iliad", "FRAFM"),
),
"212" to mapOf(
    "10" to Operator("Monaco Telecom", "MCOM2"),
),
"213" to mapOf(
    "03" to Operator("Servei De Tele. DAndorra", "ANDMA"),
),
"214" to mapOf(
    "01" to Operator("Vodafone Spain", "ESPAT"),
    "03" to Operator("Orange Espagne S.A.U", "ESPRT"),
    "07" to Operator("Telefónica Móviles España", "ESPTE"),
    "04" to Operator("Xfera Moviles SA", "ESPXF"),
),
"216" to mapOf(
    "01" to Operator("Telenor Magyarország Zrt.", "HUNH1"),
    "30" to Operator("Magyar Telekom Plc", "HUNH2"),
    "70" to Operator("Vodafone Magyarország Zrt.", "HUNVR"),
),
[…]
```

**Review by noy-wg2 — APPROVED** [review]
This looks fine to me, did not test it so trusting your testing here.

**Pull request merged**
